# Generated by Django 5.2.7 on 2025-11-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='pageentry',
            name='from_page',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pageentry',
            name='to_page',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='pageentry',
            unique_together={('user', 'book', 'from_page', 'to_page')},
        ),
    ]
